# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 819)
        MainWindow.setTabletTracking(False)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1261, 821))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.bookListWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.bookListWidget.setToolTipDuration(2)
        self.bookListWidget.setAutoFillBackground(False)
        self.bookListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
                                          "color:rgb(255, 255, 255);\n"
                                          "background: rgb(42, 51, 60)\n"
                                          "")
        self.bookListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bookListWidget.setAlternatingRowColors(False)
        self.bookListWidget.setProperty("isWrapping", False)
        self.bookListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.bookListWidget.setWordWrap(True)
        self.bookListWidget.setObjectName("bookListWidget")
        item = QtWidgets.QListWidgetItem()
        self.bookListWidget.addItem(item)
        self.gridLayout.addWidget(self.bookListWidget, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(260, 0, 381, 30))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.OverViewSceneBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.OverViewSceneBtn.setObjectName("OverViewSceneBtn")
        self.horizontalLayout.addWidget(self.OverViewSceneBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.MemorizeSceneBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.MemorizeSceneBtn.setObjectName("MemorizeSceneBtn")
        self.horizontalLayout.addWidget(self.MemorizeSceneBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.QuizSceneBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.QuizSceneBtn.setObjectName("QuizSceneBtn")
        self.horizontalLayout.addWidget(self.QuizSceneBtn)
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.OverviewScene = QtWidgets.QWidget()
        self.OverviewScene.setObjectName("OverviewScene")
        self.stackedWidget.addWidget(self.OverviewScene)
        self.MemorizeScene = QtWidgets.QWidget()
        self.MemorizeScene.setObjectName("MemorizeScene")
        self.stackedWidget.addWidget(self.MemorizeScene)
        self.QuizScene = QtWidgets.QWidget()
        self.QuizScene.setObjectName("QuizScene")
        self.stackedWidget.addWidget(self.QuizScene)
        self.gridLayout.addWidget(self.stackedWidget, 1, 2, 1, 1)
        self.lessonListWidget = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lessonListWidget.setFont(font)
        self.lessonListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lessonListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lessonListWidget.setAlternatingRowColors(True)
        self.lessonListWidget.setObjectName("lessonListWidget")
        item = QtWidgets.QListWidgetItem()
        self.lessonListWidget.addItem(item)
        self.gridLayout.addWidget(self.lessonListWidget, 1, 1, 1, 1)
        self.uploadButton = QtWidgets.QPushButton(self.layoutWidget)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setMouseTracking(False)
        self.uploadButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uploadButton.setAutoFillBackground(False)
        self.uploadButton.setStyleSheet("    background-color: green;\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: beige;\n"
                                        "    font: bold 14px;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 6px;")
        self.uploadButton.setCheckable(False)
        self.uploadButton.setFlat(False)
        self.uploadButton.setObjectName("uploadButton")
        self.gridLayout.addWidget(self.uploadButton, 0, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 16)
        self.gridLayout.setRowStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bookListWidget.setToolTip(_translate("MainWindow", "BookList"))
        self.bookListWidget.setSortingEnabled(False)
        __sortingEnabled = self.bookListWidget.isSortingEnabled()
        self.bookListWidget.setSortingEnabled(False)
        item = self.bookListWidget.item(0)
        item.setText(_translate("MainWindow", "BookList"))
        self.bookListWidget.setSortingEnabled(__sortingEnabled)
        self.OverViewSceneBtn.setText(_translate("MainWindow", "OverView"))
        self.MemorizeSceneBtn.setText(_translate("MainWindow", "Memorize"))
        self.QuizSceneBtn.setText(_translate("MainWindow", "Quiz"))
        __sortingEnabled = self.lessonListWidget.isSortingEnabled()
        self.lessonListWidget.setSortingEnabled(False)
        item = self.lessonListWidget.item(0)
        item.setText(_translate("MainWindow", "Lesson List"))
        self.lessonListWidget.setSortingEnabled(__sortingEnabled)
        self.uploadButton.setText(_translate("MainWindow", "Upload Excels"))
