# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstGui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 835)
        MainWindow.setTabletTracking(False)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1261, 841))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.bookListWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.bookListWidget.setToolTipDuration(2)
        self.bookListWidget.setAutoFillBackground(False)
        self.bookListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"color:rgb(255, 255, 255);\n"
"background: rgb(42, 51, 60)\n"
"")
        self.bookListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bookListWidget.setAlternatingRowColors(False)
        self.bookListWidget.setProperty("isWrapping", False)
        self.bookListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.bookListWidget.setWordWrap(True)
        self.bookListWidget.setObjectName("bookListWidget")
        self.gridLayout.addWidget(self.bookListWidget, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(250, 0, 381, 31))
        self.label_3.setObjectName("label_3")
        self.helpBtn = QtWidgets.QToolButton(self.frame)
        self.helpBtn.setGeometry(QtCore.QRect(900, 0, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBtn.sizePolicy().hasHeightForWidth())
        self.helpBtn.setSizePolicy(sizePolicy)
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.helpBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.helpBtn.setText("")
        self.helpBtn.setIconSize(QtCore.QSize(50, 50))
        self.helpBtn.setObjectName("helpBtn")
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setEnabled(False)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.OverviewScene = QtWidgets.QWidget()
        self.OverviewScene.setObjectName("OverviewScene")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 70, 571, 671))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wordListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.wordListWidget.setProperty("showDropIndicator", False)
        self.wordListWidget.setAlternatingRowColors(True)
        self.wordListWidget.setObjectName("wordListWidget")
        self.horizontalLayout_2.addWidget(self.wordListWidget)
        self.meaningListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.meaningListWidget.setProperty("showDropIndicator", False)
        self.meaningListWidget.setAlternatingRowColors(True)
        self.meaningListWidget.setWordWrap(False)
        self.meaningListWidget.setObjectName("meaningListWidget")
        self.horizontalLayout_2.addWidget(self.meaningListWidget)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(80, 0, 571, 89))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.WordLabel_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.WordLabel_0.setObjectName("WordLabel_0")
        self.horizontalLayout_3.addWidget(self.WordLabel_0)
        self.MeaningLabel_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MeaningLabel_0.setObjectName("MeaningLabel_0")
        self.horizontalLayout_3.addWidget(self.MeaningLabel_0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(720, 150, 191, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MemorizeBtn_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.MemorizeBtn_0.setFont(font)
        self.MemorizeBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MemorizeBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.MemorizeBtn_0.setObjectName("MemorizeBtn_0")
        self.verticalLayout.addWidget(self.MemorizeBtn_0)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.QuizBtn_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_0.sizePolicy().hasHeightForWidth())
        self.QuizBtn_0.setSizePolicy(sizePolicy)
        self.QuizBtn_0.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.QuizBtn_0.setFont(font)
        self.QuizBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_0.setObjectName("QuizBtn_0")
        self.verticalLayout.addWidget(self.QuizBtn_0)
        self.stackedWidget.addWidget(self.OverviewScene)
        self.MemorizeScene = QtWidgets.QWidget()
        self.MemorizeScene.setObjectName("MemorizeScene")
        self.stackedWidget.addWidget(self.MemorizeScene)
        self.QuizScene = QtWidgets.QWidget()
        self.QuizScene.setObjectName("QuizScene")
        self.stackedWidget.addWidget(self.QuizScene)
        self.gridLayout.addWidget(self.stackedWidget, 1, 2, 1, 1)
        self.lessonListWidget = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lessonListWidget.setFont(font)
        self.lessonListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.lessonListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lessonListWidget.setAlternatingRowColors(True)
        self.lessonListWidget.setObjectName("lessonListWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        self.gridLayout.addWidget(self.lessonListWidget, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uploadButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.uploadButton.sizePolicy().hasHeightForWidth())
        self.uploadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.uploadButton.setFont(font)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setMouseTracking(False)
        self.uploadButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uploadButton.setAutoFillBackground(False)
        self.uploadButton.setStyleSheet("    background-color: rgb(170, 255, 127);\n"
"    border-style: outset;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    border-color: green;\n"
"    font: bold 20px;\n"
"    min-width: 10em;\n"
"    padding: 6px;")
        self.uploadButton.setIconSize(QtCore.QSize(30, 30))
        self.uploadButton.setCheckable(False)
        self.uploadButton.setFlat(False)
        self.uploadButton.setObjectName("uploadButton")
        self.verticalLayout_2.addWidget(self.uploadButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 16)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bookListWidget.setToolTip(_translate("MainWindow", "BookList"))
        self.bookListWidget.setSortingEnabled(False)
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">This is the record of your Progess</span></p></body></html>"))
        self.WordLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#ff4ea4;\">Word</span></p></body></html>"))
        self.MeaningLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#4e7af3;\">Meaning</span></p></body></html>"))
        self.MemorizeBtn_0.setText(_translate("MainWindow", "Memorize"))
        self.QuizBtn_0.setText(_translate("MainWindow", "Quiz"))
        __sortingEnabled = self.lessonListWidget.isSortingEnabled()
        self.lessonListWidget.setSortingEnabled(False)
        item = self.lessonListWidget.item(0)
        item.setText(_translate("MainWindow", "请"))
        item = self.lessonListWidget.item(1)
        item.setText(_translate("MainWindow", "先"))
        item = self.lessonListWidget.item(2)
        item.setText(_translate("MainWindow", "选"))
        item = self.lessonListWidget.item(3)
        item.setText(_translate("MainWindow", "择"))
        item = self.lessonListWidget.item(4)
        item.setText(_translate("MainWindow", "一"))
        item = self.lessonListWidget.item(5)
        item.setText(_translate("MainWindow", "本"))
        item = self.lessonListWidget.item(6)
        item.setText(_translate("MainWindow", "书"))
        self.lessonListWidget.setSortingEnabled(__sortingEnabled)
        self.uploadButton.setText(_translate("MainWindow", "Upload Excels"))
        self.uploadButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
