# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstGui_ChineseVersion.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1259, 878)
        MainWindow.setTabletTracking(False)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1261, 881))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.layoutWidget)
        self.widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.widget.setAutoFillBackground(True)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.exitBtn = QtWidgets.QToolButton(self.widget)
        self.exitBtn.setGeometry(QtCore.QRect(1220, 0, 31, 31))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setStyleSheet("background-color: rgb(255,255,255,0)\n"
"")
        self.exitBtn.setText("")
        self.exitBtn.setIconSize(QtCore.QSize(20, 20))
        self.exitBtn.setObjectName("exitBtn")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setEnabled(False)
        self.label.setGeometry(QtCore.QRect(500, -8, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.TitleBar_Label = QtWidgets.QLabel(self.widget)
        self.TitleBar_Label.setEnabled(True)
        self.TitleBar_Label.setGeometry(QtCore.QRect(-21, -14, 1281, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleBar_Label.sizePolicy().hasHeightForWidth())
        self.TitleBar_Label.setSizePolicy(sizePolicy)
        self.TitleBar_Label.setStyleSheet("background-color: black")
        self.TitleBar_Label.setText("")
        self.TitleBar_Label.setObjectName("TitleBar_Label")
        self.miniBtn = QtWidgets.QToolButton(self.widget)
        self.miniBtn.setGeometry(QtCore.QRect(1190, 0, 31, 31))
        self.miniBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.miniBtn.setStyleSheet("background-color: rgb(255,255,255,0)\n"
"")
        self.miniBtn.setText("")
        self.miniBtn.setIconSize(QtCore.QSize(20, 20))
        self.miniBtn.setObjectName("miniBtn")
        self.TitleBar_Label.raise_()
        self.exitBtn.raise_()
        self.label.raise_()
        self.miniBtn.raise_()
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 3)
        self.lessonListWidget = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lessonListWidget.setFont(font)
        self.lessonListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lessonListWidget.setAutoFillBackground(True)
        self.lessonListWidget.setStyleSheet("background-color:rgb(252, 252, 252)")
        self.lessonListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lessonListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lessonListWidget.setAlternatingRowColors(True)
        self.lessonListWidget.setObjectName("lessonListWidget")
        self.gridLayout.addWidget(self.lessonListWidget, 2, 1, 5, 1)
        self.bookListWidget = QtWidgets.QListWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookListWidget.sizePolicy().hasHeightForWidth())
        self.bookListWidget.setSizePolicy(sizePolicy)
        self.bookListWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.bookListWidget.setToolTipDuration(-1)
        self.bookListWidget.setAutoFillBackground(True)
        self.bookListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font-style: bold;\n"
"color:rgb(255, 255, 255);\n"
"background: rgb(42, 51, 60)\n"
"")
        self.bookListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bookListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bookListWidget.setAlternatingRowColors(False)
        self.bookListWidget.setProperty("isWrapping", False)
        self.bookListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.bookListWidget.setWordWrap(True)
        self.bookListWidget.setObjectName("bookListWidget")
        self.gridLayout.addWidget(self.bookListWidget, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uploadButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.uploadButton.sizePolicy().hasHeightForWidth())
        self.uploadButton.setSizePolicy(sizePolicy)
        self.uploadButton.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.uploadButton.setFont(font)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setMouseTracking(False)
        self.uploadButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uploadButton.setAutoFillBackground(False)
        self.uploadButton.setStyleSheet("background-color:rgb(204, 255, 153);\n"
"    color: black;\n"
"    font: bold 20px;\n"
"")
        self.uploadButton.setIconSize(QtCore.QSize(30, 30))
        self.uploadButton.setCheckable(False)
        self.uploadButton.setAutoDefault(False)
        self.uploadButton.setDefault(True)
        self.uploadButton.setFlat(False)
        self.uploadButton.setObjectName("uploadButton")
        self.verticalLayout_2.addWidget(self.uploadButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressLabel = QtWidgets.QLabel(self.frame)
        self.progressLabel.setGeometry(QtCore.QRect(0, 0, 961, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressLabel.setFont(font)
        self.progressLabel.setStyleSheet("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout.addWidget(self.frame, 1, 2, 1, 1)
        self.frame1 = QtWidgets.QFrame(self.layoutWidget)
        self.frame1.setObjectName("frame1")
        self.gridLayout.addWidget(self.frame1, 5, 0, 1, 1)
        self.addBookBtn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBookBtn.sizePolicy().hasHeightForWidth())
        self.addBookBtn.setSizePolicy(sizePolicy)
        self.addBookBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.addBookBtn.setBaseSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addBookBtn.setFont(font)
        self.addBookBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBookBtn.setStyleSheet("background-color: rgb(27, 33, 39);\n"
"color: white;")
        self.addBookBtn.setIconSize(QtCore.QSize(30, 30))
        self.addBookBtn.setObjectName("addBookBtn")
        self.gridLayout.addWidget(self.addBookBtn, 3, 0, 2, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.OverviewScene = QtWidgets.QWidget()
        self.OverviewScene.setAutoFillBackground(False)
        self.OverviewScene.setObjectName("OverviewScene")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 70, 571, 671))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wordListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.wordListWidget.setStyleSheet("background-color: rgba(255, 255, 255,200)")
        self.wordListWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.wordListWidget.setProperty("showDropIndicator", False)
        self.wordListWidget.setAlternatingRowColors(True)
        self.wordListWidget.setWordWrap(False)
        self.wordListWidget.setObjectName("wordListWidget")
        self.horizontalLayout_2.addWidget(self.wordListWidget)
        self.meaningListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.meaningListWidget.setStyleSheet("background-color: rgba(255,255,255,200)")
        self.meaningListWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.meaningListWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.meaningListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.meaningListWidget.setAutoScroll(True)
        self.meaningListWidget.setProperty("showDropIndicator", True)
        self.meaningListWidget.setAlternatingRowColors(True)
        self.meaningListWidget.setObjectName("meaningListWidget")
        self.horizontalLayout_2.addWidget(self.meaningListWidget)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(80, 0, 571, 89))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.WordLabel_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.WordLabel_0.setFont(font)
        self.WordLabel_0.setObjectName("WordLabel_0")
        self.horizontalLayout_3.addWidget(self.WordLabel_0)
        self.MeaningLabel_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MeaningLabel_0.setFont(font)
        self.MeaningLabel_0.setObjectName("MeaningLabel_0")
        self.horizontalLayout_3.addWidget(self.MeaningLabel_0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(720, 150, 211, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MemorizeBtn_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MemorizeBtn_0.setFont(font)
        self.MemorizeBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MemorizeBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.MemorizeBtn_0.setObjectName("MemorizeBtn_0")
        self.verticalLayout.addWidget(self.MemorizeBtn_0)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.QuizBtn_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_0.sizePolicy().hasHeightForWidth())
        self.QuizBtn_0.setSizePolicy(sizePolicy)
        self.QuizBtn_0.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuizBtn_0.setFont(font)
        self.QuizBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_0.setObjectName("QuizBtn_0")
        self.verticalLayout.addWidget(self.QuizBtn_0)
        self.frame_5 = QtWidgets.QFrame(self.OverviewScene)
        self.frame_5.setGeometry(QtCore.QRect(0, 20, 959, 730))
        self.frame_5.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget.raise_()
        self.stackedWidget.addWidget(self.OverviewScene)
        self.MemorizeScene = QtWidgets.QWidget()
        self.MemorizeScene.setAutoFillBackground(False)
        self.MemorizeScene.setStyleSheet("")
        self.MemorizeScene.setObjectName("MemorizeScene")
        self.wordBox = QtWidgets.QGroupBox(self.MemorizeScene)
        self.wordBox.setGeometry(QtCore.QRect(240, 100, 420, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.wordBox.setFont(font)
        self.wordBox.setAutoFillBackground(False)
        self.wordBox.setStyleSheet("color: blue;")
        self.wordBox.setFlat(False)
        self.wordBox.setCheckable(False)
        self.wordBox.setObjectName("wordBox")
        self.wordBrowser = QtWidgets.QTextBrowser(self.wordBox)
        self.wordBrowser.setGeometry(QtCore.QRect(0, 40, 420, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.wordBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.wordBrowser.setFont(font)
        self.wordBrowser.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:black;")
        self.wordBrowser.setObjectName("wordBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.MemorizeScene)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 250, 420, 271))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color:blue;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.meaningBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.meaningBrowser.setGeometry(QtCore.QRect(0, 40, 420, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.meaningBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meaningBrowser.setFont(font)
        self.meaningBrowser.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color: black；\n"
"")
        self.meaningBrowser.setAcceptRichText(True)
        self.meaningBrowser.setObjectName("meaningBrowser")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.MemorizeScene)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 590, 781, 121))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setMinimumSize(QtCore.QSize(20, 10))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backBtn.setFont(font)
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.backBtn.setText("")
        self.backBtn.setIconSize(QtCore.QSize(100, 100))
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.translateBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateBtn.sizePolicy().hasHeightForWidth())
        self.translateBtn.setSizePolicy(sizePolicy)
        self.translateBtn.setMinimumSize(QtCore.QSize(20, 5))
        self.translateBtn.setBaseSize(QtCore.QSize(20, 10))
        self.translateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.translateBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.translateBtn.setText("")
        self.translateBtn.setIconSize(QtCore.QSize(100, 100))
        self.translateBtn.setObjectName("translateBtn")
        self.horizontalLayout.addWidget(self.translateBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.NextBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextBtn.sizePolicy().hasHeightForWidth())
        self.NextBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NextBtn.setFont(font)
        self.NextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.NextBtn.setText("")
        self.NextBtn.setIconSize(QtCore.QSize(100, 100))
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout.addWidget(self.NextBtn)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.MemorizeScene)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(730, 120, 211, 291))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MenuBtn_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MenuBtn_1.setFont(font)
        self.MenuBtn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.MenuBtn_1.setObjectName("MenuBtn_1")
        self.verticalLayout_3.addWidget(self.MenuBtn_1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.QuizBtn_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.QuizBtn_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_1.sizePolicy().hasHeightForWidth())
        self.QuizBtn_1.setSizePolicy(sizePolicy)
        self.QuizBtn_1.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuizBtn_1.setFont(font)
        self.QuizBtn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_1.setObjectName("QuizBtn_1")
        self.verticalLayout_3.addWidget(self.QuizBtn_1)
        self.countBrowser_1 = QtWidgets.QTextBrowser(self.MemorizeScene)
        self.countBrowser_1.setGeometry(QtCore.QRect(20, 100, 191, 151))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.countBrowser_1.setFont(font)
        self.countBrowser_1.setStyleSheet("background-color:rgba(227, 227, 227,100);\n"
"border-style: insert;\n"
"border-width: 1px;\n"
"border-radius: 50px;\n"
"border-color: green;\n"
"padding:20px")
        self.countBrowser_1.setObjectName("countBrowser_1")
        self.showBtn = QtWidgets.QPushButton(self.MemorizeScene)
        self.showBtn.setGeometry(QtCore.QRect(380, 540, 161, 71))
        self.showBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.showBtn.setText("")
        self.showBtn.setIconSize(QtCore.QSize(50, 50))
        self.showBtn.setObjectName("showBtn")
        self.proUSBtn = QtWidgets.QToolButton(self.MemorizeScene)
        self.proUSBtn.setGeometry(QtCore.QRect(360, 230, 71, 71))
        self.proUSBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proUSBtn.setStyleSheet("background-color: transparent;")
        self.proUSBtn.setText("")
        self.proUSBtn.setIconSize(QtCore.QSize(50, 50))
        self.proUSBtn.setObjectName("proUSBtn")
        self.proENGBtn = QtWidgets.QToolButton(self.MemorizeScene)
        self.proENGBtn.setGeometry(QtCore.QRect(500, 230, 81, 71))
        self.proENGBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proENGBtn.setStyleSheet("background-color: transparent;")
        self.proENGBtn.setText("")
        self.proENGBtn.setIconSize(QtCore.QSize(50, 50))
        self.proENGBtn.setObjectName("proENGBtn")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.MemorizeScene)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(320, 190, 271, 51))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.starBtn_2 = QtWidgets.QToolButton(self.horizontalLayoutWidget_7)
        self.starBtn_2.setStyleSheet("background-color:transparent;")
        self.starBtn_2.setText("")
        self.starBtn_2.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_2.setObjectName("starBtn_2")
        self.horizontalLayout_4.addWidget(self.starBtn_2)
        self.starBtn_1 = QtWidgets.QToolButton(self.horizontalLayoutWidget_7)
        self.starBtn_1.setStyleSheet("background-color:transparent;")
        self.starBtn_1.setText("")
        self.starBtn_1.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_1.setObjectName("starBtn_1")
        self.horizontalLayout_4.addWidget(self.starBtn_1)
        self.starBtn_3 = QtWidgets.QToolButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starBtn_3.sizePolicy().hasHeightForWidth())
        self.starBtn_3.setSizePolicy(sizePolicy)
        self.starBtn_3.setStyleSheet("background-color:transparent;")
        self.starBtn_3.setText("")
        self.starBtn_3.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_3.setObjectName("starBtn_3")
        self.horizontalLayout_4.addWidget(self.starBtn_3)
        self.starBtn_4 = QtWidgets.QToolButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.starBtn_4.sizePolicy().hasHeightForWidth())
        self.starBtn_4.setSizePolicy(sizePolicy)
        self.starBtn_4.setMinimumSize(QtCore.QSize(30, 30))
        self.starBtn_4.setStyleSheet("background-color:transparent;")
        self.starBtn_4.setText("")
        self.starBtn_4.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_4.setObjectName("starBtn_4")
        self.horizontalLayout_4.addWidget(self.starBtn_4)
        self.starBtn_5 = QtWidgets.QToolButton(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starBtn_5.sizePolicy().hasHeightForWidth())
        self.starBtn_5.setSizePolicy(sizePolicy)
        self.starBtn_5.setStyleSheet("background-color:transparent;")
        self.starBtn_5.setText("")
        self.starBtn_5.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_5.setObjectName("starBtn_5")
        self.horizontalLayout_4.addWidget(self.starBtn_5)
        self.PreSufBox = QtWidgets.QGroupBox(self.MemorizeScene)
        self.PreSufBox.setGeometry(QtCore.QRect(20, 250, 200, 270))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PreSufBox.setFont(font)
        self.PreSufBox.setStyleSheet("color: blue;")
        self.PreSufBox.setObjectName("PreSufBox")
        self.PreSufBrowser = QtWidgets.QTextEdit(self.MemorizeScene)
        self.PreSufBrowser.setGeometry(QtCore.QRect(20, 290, 200, 230))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.PreSufBrowser.setFont(font)
        self.PreSufBrowser.setStyleSheet("color:black;")
        self.PreSufBrowser.setObjectName("PreSufBrowser")
        self.wordPic = QtWidgets.QLabel(self.MemorizeScene)
        self.wordPic.setGeometry(QtCore.QRect(700, 180, 241, 261))
        self.wordPic.setText("")
        self.wordPic.setObjectName("wordPic")
        self.frame_4 = QtWidgets.QFrame(self.MemorizeScene)
        self.frame_4.setGeometry(QtCore.QRect(0, 20, 959, 730))
        self.frame_4.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.MemorizeScene)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(320, 90, 341, 51))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tag_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.tag_1.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tag_1.setFont(font)
        self.tag_1.setStyleSheet("background-color:transparent;")
        self.tag_1.setText("")
        self.tag_1.setObjectName("tag_1")
        self.horizontalLayout_5.addWidget(self.tag_1)
        self.tag_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.tag_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tag_2.setFont(font)
        self.tag_2.setStyleSheet("background-color:transparent;")
        self.tag_2.setText("")
        self.tag_2.setObjectName("tag_2")
        self.horizontalLayout_5.addWidget(self.tag_2)
        self.tag_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.tag_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tag_3.setFont(font)
        self.tag_3.setStyleSheet("background-color:transparent;")
        self.tag_3.setText("")
        self.tag_3.setObjectName("tag_3")
        self.horizontalLayout_5.addWidget(self.tag_3)
        self.tag_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.tag_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.tag_4.setFont(font)
        self.tag_4.setStyleSheet("background-color:transparent;")
        self.tag_4.setText("")
        self.tag_4.setObjectName("tag_4")
        self.horizontalLayout_5.addWidget(self.tag_4)
        self.frame_4.raise_()
        self.wordPic.raise_()
        self.wordBox.raise_()
        self.groupBox_2.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.countBrowser_1.raise_()
        self.showBtn.raise_()
        self.proUSBtn.raise_()
        self.proENGBtn.raise_()
        self.horizontalLayoutWidget_7.raise_()
        self.PreSufBox.raise_()
        self.PreSufBrowser.raise_()
        self.horizontalLayoutWidget_8.raise_()
        self.stackedWidget.addWidget(self.MemorizeScene)
        self.QuizScene = QtWidgets.QWidget()
        self.QuizScene.setObjectName("QuizScene")
        self.hintEdit = QtWidgets.QLineEdit(self.QuizScene)
        self.hintEdit.setGeometry(QtCore.QRect(90, 500, 500, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hintEdit.setFont(font)
        self.hintEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hintEdit.setStyleSheet("border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(255,255,255,0);\n"
"border-width: 1px;")
        self.hintEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.hintEdit.setReadOnly(True)
        self.hintEdit.setObjectName("hintEdit")
        self.enterEdit = QtWidgets.QLineEdit(self.QuizScene)
        self.enterEdit.setGeometry(QtCore.QRect(90, 620, 500, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enterEdit.setFont(font)
        self.enterEdit.setStyleSheet("border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(255, 170, 255);\n"
"border-width: 1px;")
        self.enterEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enterEdit.setObjectName("enterEdit")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.QuizScene)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(710, 30, 211, 91))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MenuBtn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MenuBtn_2.setFont(font)
        self.MenuBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn_2.setIconSize(QtCore.QSize(40, 40))
        self.MenuBtn_2.setObjectName("MenuBtn_2")
        self.verticalLayout_4.addWidget(self.MenuBtn_2)
        self.wordEnterListWidget = QtWidgets.QListWidget(self.QuizScene)
        self.wordEnterListWidget.setGeometry(QtCore.QRect(690, 180, 251, 501))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.wordEnterListWidget.setFont(font)
        self.wordEnterListWidget.setStyleSheet("background-color: rgba(255, 255, 255, 150)")
        self.wordEnterListWidget.setAlternatingRowColors(True)
        self.wordEnterListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.wordEnterListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.wordEnterListWidget.setUniformItemSizes(False)
        self.wordEnterListWidget.setObjectName("wordEnterListWidget")
        self.remainLabel = QtWidgets.QLabel(self.QuizScene)
        self.remainLabel.setGeometry(QtCore.QRect(690, 130, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remainLabel.setFont(font)
        self.remainLabel.setStyleSheet("border-style: outset;\n"
"border-color: green;\n"
"border-width:1px;\n"
"border-radius: 15px;")
        self.remainLabel.setObjectName("remainLabel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.QuizScene)
        self.groupBox_3.setGeometry(QtCore.QRect(90, 100, 500, 271))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color:blue;\n"
"border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(0,0,0);\n"
"border-width: 1px;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.meaningBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.meaningBrowser_2.setGeometry(QtCore.QRect(0, 40, 500, 230))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.meaningBrowser_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meaningBrowser_2.setFont(font)
        self.meaningBrowser_2.setStyleSheet("color: black;\n"
"border-style: insert;\n"
"border-radius:15;\n"
"border-color:black;\n"
"border-width: 1px;")
        self.meaningBrowser_2.setAcceptRichText(True)
        self.meaningBrowser_2.setObjectName("meaningBrowser_2")
        self.statusBtn = QtWidgets.QToolButton(self.QuizScene)
        self.statusBtn.setGeometry(QtCore.QRect(290, 380, 111, 111))
        self.statusBtn.setStyleSheet("background-color:rgba(255,255,255,0)")
        self.statusBtn.setText("")
        self.statusBtn.setIconSize(QtCore.QSize(100, 100))
        self.statusBtn.setObjectName("statusBtn")
        self.quizLabel = QtWidgets.QLabel(self.QuizScene)
        self.quizLabel.setGeometry(QtCore.QRect(50, 20, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quizLabel.setFont(font)
        self.quizLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quizLabel.setObjectName("quizLabel")
        self.frame_3 = QtWidgets.QFrame(self.QuizScene)
        self.frame_3.setGeometry(QtCore.QRect(0, 20, 959, 730))
        self.frame_3.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.translateBtn_2 = QtWidgets.QPushButton(self.QuizScene)
        self.translateBtn_2.setGeometry(QtCore.QRect(490, 270, 101, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateBtn_2.sizePolicy().hasHeightForWidth())
        self.translateBtn_2.setSizePolicy(sizePolicy)
        self.translateBtn_2.setMinimumSize(QtCore.QSize(20, 5))
        self.translateBtn_2.setBaseSize(QtCore.QSize(20, 10))
        self.translateBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.translateBtn_2.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.translateBtn_2.setText("")
        self.translateBtn_2.setIconSize(QtCore.QSize(100, 100))
        self.translateBtn_2.setObjectName("translateBtn_2")
        self.proUSBtn_2 = QtWidgets.QToolButton(self.QuizScene)
        self.proUSBtn_2.setGeometry(QtCore.QRect(210, 400, 71, 71))
        self.proUSBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proUSBtn_2.setStyleSheet("background-color: transparent;")
        self.proUSBtn_2.setText("")
        self.proUSBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.proUSBtn_2.setObjectName("proUSBtn_2")
        self.proENGBtn_2 = QtWidgets.QToolButton(self.QuizScene)
        self.proENGBtn_2.setGeometry(QtCore.QRect(410, 400, 81, 71))
        self.proENGBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proENGBtn_2.setStyleSheet("background-color: transparent;")
        self.proENGBtn_2.setText("")
        self.proENGBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.proENGBtn_2.setObjectName("proENGBtn_2")
        self.frame_3.raise_()
        self.groupBox_3.raise_()
        self.wordEnterListWidget.raise_()
        self.hintEdit.raise_()
        self.enterEdit.raise_()
        self.horizontalLayoutWidget_6.raise_()
        self.remainLabel.raise_()
        self.statusBtn.raise_()
        self.quizLabel.raise_()
        self.translateBtn_2.raise_()
        self.proUSBtn_2.raise_()
        self.proENGBtn_2.raise_()
        self.stackedWidget.addWidget(self.QuizScene)
        self.page = QtWidgets.QWidget()
        self.page.setAutoFillBackground(False)
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 140, 681, 621))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setStyleSheet("background-color: rgb(255,255,255,0);\n"
"border-style: insert")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_5.addWidget(self.textEdit)
        self.toolButton_2 = QtWidgets.QToolButton(self.page)
        self.toolButton_2.setEnabled(False)
        self.toolButton_2.setGeometry(QtCore.QRect(425, 553, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3 = QtWidgets.QToolButton(self.page)
        self.toolButton_3.setEnabled(False)
        self.toolButton_3.setGeometry(QtCore.QRect(500, 553, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setStyleSheet("\n"
"color: blue;\n"
"background-color: rgba(164, 255, 195, 0)")
        self.toolButton_3.setObjectName("toolButton_3")
        self.frame_6 = QtWidgets.QFrame(self.page)
        self.frame_6.setGeometry(QtCore.QRect(0, 20, 959, 730))
        self.frame_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.frame_6.setToolTipDuration(-2)
        self.frame_6.setAutoFillBackground(False)
        self.frame_6.setStyleSheet("background-color: rgba(240, 240, 240,120);\n"
"border-style: outset;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.toolButton_4 = QtWidgets.QToolButton(self.page)
        self.toolButton_4.setEnabled(False)
        self.toolButton_4.setGeometry(QtCore.QRect(425, 597, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_4.setObjectName("toolButton_4")
        self.toolButton_5 = QtWidgets.QToolButton(self.page)
        self.toolButton_5.setEnabled(False)
        self.toolButton_5.setGeometry(QtCore.QRect(500, 597, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_5.setObjectName("toolButton_5")
        self.frame_6.raise_()
        self.verticalLayoutWidget.raise_()
        self.toolButton_2.raise_()
        self.toolButton_3.raise_()
        self.toolButton_4.raise_()
        self.toolButton_5.raise_()
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 2, 2, 5, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 16)
        self.gridLayout.setRowStretch(0, 2)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 60)
        self.gridLayout.setRowStretch(4, 4)
        self.frame.raise_()
        self.lessonListWidget.raise_()
        self.frame.raise_()
        self.stackedWidget.raise_()
        self.bookListWidget.raise_()
        self.addBookBtn.raise_()
        self.helpBtn = QtWidgets.QToolButton(self.centralwidget)
        self.helpBtn.setGeometry(QtCore.QRect(1190, 30, 51, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBtn.sizePolicy().hasHeightForWidth())
        self.helpBtn.setSizePolicy(sizePolicy)
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.helpBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.helpBtn.setText("")
        self.helpBtn.setIconSize(QtCore.QSize(50, 50))
        self.helpBtn.setObjectName("helpBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exitBtn.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#ffffff;\">RemV</span></p></body></html>"))
        self.miniBtn.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.lessonListWidget.setToolTip(_translate("MainWindow", "选课列表"))
        self.bookListWidget.setSortingEnabled(False)
        self.uploadButton.setText(_translate("MainWindow", "上传Excel文档"))
        self.uploadButton.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.progressLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:normal;\">上次学习进度： SAT Vocabularies, Lesson 1, 共学习 ———— 词</span></p></body></html>"))
        self.addBookBtn.setText(_translate("MainWindow", "快速录入错词"))
        self.WordLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#834100;\">单词</span></p></body></html>"))
        self.MeaningLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">词义</span></p></body></html>"))
        self.MemorizeBtn_0.setText(_translate("MainWindow", "背单词"))
        self.QuizBtn_0.setText(_translate("MainWindow", "小测"))
        self.wordBox.setTitle(_translate("MainWindow", "单词"))
        self.wordBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:italic;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-weight:400; font-style:normal;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "词义"))
        self.meaningBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-style:italic;\"><br /></p></body></html>"))
        self.MenuBtn_1.setText(_translate("MainWindow", "主页"))
        self.QuizBtn_1.setText(_translate("MainWindow", "小测"))
        self.countBrowser_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:48pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:48px;\"><br /></p></body></html>"))
        self.PreSufBox.setTitle(_translate("MainWindow", "词跟 词缀"))
        self.MenuBtn_2.setText(_translate("MainWindow", "主页"))
        self.remainLabel.setText(_translate("MainWindow", "剩余:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "词义"))
        self.meaningBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-style:italic;\"><br /></p></body></html>"))
        self.quizLabel.setText(_translate("MainWindow", "Tmp"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:7.8pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">在左侧选择一本单词书</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">或者点击上传按钮 上传自己的单词书</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">自己的单词书必须是excel形式（*.xlsx）</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">第一列： 单词</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">第二列： 词性</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">第三列： 词义</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">单词为必填项</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">快捷键</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">上传:        +         </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">关闭:        +         </span></p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "Ctrl"))
        self.toolButton_3.setText(_translate("MainWindow", "U"))
        self.toolButton_4.setText(_translate("MainWindow", "Ctrl"))
        self.toolButton_5.setText(_translate("MainWindow", "X"))
