# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstGui_ChineseVersion.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 835)
        MainWindow.setTabletTracking(False)
        MainWindow.setWindowOpacity(0.98)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1261, 841))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.bookListWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.bookListWidget.setToolTipDuration(2)
        self.bookListWidget.setAutoFillBackground(True)
        self.bookListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font-style: bold;\n"
"color:rgb(255, 255, 255);\n"
"background: rgb(42, 51, 60)\n"
"")
        self.bookListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bookListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bookListWidget.setAlternatingRowColors(False)
        self.bookListWidget.setProperty("isWrapping", False)
        self.bookListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.bookListWidget.setWordWrap(True)
        self.bookListWidget.setObjectName("bookListWidget")
        self.gridLayout.addWidget(self.bookListWidget, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressLabel = QtWidgets.QLabel(self.frame)
        self.progressLabel.setGeometry(QtCore.QRect(0, 0, 961, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressLabel.setFont(font)
        self.progressLabel.setStyleSheet("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.helpBtn = QtWidgets.QToolButton(self.frame)
        self.helpBtn.setGeometry(QtCore.QRect(900, 0, 51, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBtn.sizePolicy().hasHeightForWidth())
        self.helpBtn.setSizePolicy(sizePolicy)
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.helpBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.helpBtn.setText("")
        self.helpBtn.setIconSize(QtCore.QSize(50, 50))
        self.helpBtn.setObjectName("helpBtn")
        self.gridLayout.addWidget(self.frame, 0, 2, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.OverviewScene = QtWidgets.QWidget()
        self.OverviewScene.setAutoFillBackground(False)
        self.OverviewScene.setObjectName("OverviewScene")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 70, 571, 671))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wordListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.wordListWidget.setStyleSheet("background-color: rgba(255, 255, 255,220)")
        self.wordListWidget.setProperty("showDropIndicator", False)
        self.wordListWidget.setAlternatingRowColors(True)
        self.wordListWidget.setObjectName("wordListWidget")
        self.horizontalLayout_2.addWidget(self.wordListWidget)
        self.meaningListWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.meaningListWidget.setStyleSheet("background-color: rgba(255, 255, 255,220)")
        self.meaningListWidget.setProperty("showDropIndicator", False)
        self.meaningListWidget.setAlternatingRowColors(True)
        self.meaningListWidget.setWordWrap(False)
        self.meaningListWidget.setObjectName("meaningListWidget")
        self.horizontalLayout_2.addWidget(self.meaningListWidget)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(80, 0, 571, 89))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.WordLabel_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.WordLabel_0.setFont(font)
        self.WordLabel_0.setObjectName("WordLabel_0")
        self.horizontalLayout_3.addWidget(self.WordLabel_0)
        self.MeaningLabel_0 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MeaningLabel_0.setFont(font)
        self.MeaningLabel_0.setObjectName("MeaningLabel_0")
        self.horizontalLayout_3.addWidget(self.MeaningLabel_0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.OverviewScene)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(720, 150, 211, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MemorizeBtn_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MemorizeBtn_0.setFont(font)
        self.MemorizeBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MemorizeBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.MemorizeBtn_0.setObjectName("MemorizeBtn_0")
        self.verticalLayout.addWidget(self.MemorizeBtn_0)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.QuizBtn_0 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_0.sizePolicy().hasHeightForWidth())
        self.QuizBtn_0.setSizePolicy(sizePolicy)
        self.QuizBtn_0.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuizBtn_0.setFont(font)
        self.QuizBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_0.setObjectName("QuizBtn_0")
        self.verticalLayout.addWidget(self.QuizBtn_0)
        self.frame_5 = QtWidgets.QFrame(self.OverviewScene)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 959, 787))
        self.frame_5.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.horizontalLayoutWidget.raise_()
        self.stackedWidget.addWidget(self.OverviewScene)
        self.MemorizeScene = QtWidgets.QWidget()
        self.MemorizeScene.setAutoFillBackground(False)
        self.MemorizeScene.setStyleSheet("")
        self.MemorizeScene.setObjectName("MemorizeScene")
        self.groupBox = QtWidgets.QGroupBox(self.MemorizeScene)
        self.groupBox.setGeometry(QtCore.QRect(240, 100, 420, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color:blue")
        self.groupBox.setObjectName("groupBox")
        self.wordBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.wordBrowser.setGeometry(QtCore.QRect(0, 40, 420, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.wordBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.wordBrowser.setFont(font)
        self.wordBrowser.setStyleSheet("color:black;")
        self.wordBrowser.setObjectName("wordBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.MemorizeScene)
        self.groupBox_2.setGeometry(QtCore.QRect(240, 250, 420, 271))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("color:blue;")
        self.groupBox_2.setObjectName("groupBox_2")
        self.meaningBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.meaningBrowser.setGeometry(QtCore.QRect(0, 40, 420, 231))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.meaningBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meaningBrowser.setFont(font)
        self.meaningBrowser.setStyleSheet("color: black")
        self.meaningBrowser.setAcceptRichText(True)
        self.meaningBrowser.setObjectName("meaningBrowser")
        self.showBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.showBtn.setGeometry(QtCore.QRect(320, 210, 161, 71))
        self.showBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.showBtn.setText("")
        self.showBtn.setIconSize(QtCore.QSize(50, 50))
        self.showBtn.setObjectName("showBtn")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.MemorizeScene)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 590, 781, 121))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setMinimumSize(QtCore.QSize(20, 10))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backBtn.setFont(font)
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.backBtn.setText("")
        self.backBtn.setIconSize(QtCore.QSize(100, 100))
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.translateBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateBtn.sizePolicy().hasHeightForWidth())
        self.translateBtn.setSizePolicy(sizePolicy)
        self.translateBtn.setMinimumSize(QtCore.QSize(20, 5))
        self.translateBtn.setBaseSize(QtCore.QSize(20, 10))
        self.translateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.translateBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.translateBtn.setText("")
        self.translateBtn.setIconSize(QtCore.QSize(100, 100))
        self.translateBtn.setObjectName("translateBtn")
        self.horizontalLayout.addWidget(self.translateBtn)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.NextBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextBtn.sizePolicy().hasHeightForWidth())
        self.NextBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NextBtn.setFont(font)
        self.NextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.NextBtn.setText("")
        self.NextBtn.setIconSize(QtCore.QSize(100, 100))
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout.addWidget(self.NextBtn)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.MemorizeScene)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(730, 120, 211, 291))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MenuBtn_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MenuBtn_1.setFont(font)
        self.MenuBtn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.MenuBtn_1.setObjectName("MenuBtn_1")
        self.verticalLayout_3.addWidget(self.MenuBtn_1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.QuizBtn_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.QuizBtn_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_1.sizePolicy().hasHeightForWidth())
        self.QuizBtn_1.setSizePolicy(sizePolicy)
        self.QuizBtn_1.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuizBtn_1.setFont(font)
        self.QuizBtn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_1.setObjectName("QuizBtn_1")
        self.verticalLayout_3.addWidget(self.QuizBtn_1)
        self.countBrowser_1 = QtWidgets.QTextBrowser(self.MemorizeScene)
        self.countBrowser_1.setGeometry(QtCore.QRect(20, 190, 191, 151))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.countBrowser_1.setFont(font)
        self.countBrowser_1.setStyleSheet("background-color:rgba(227, 227, 227,100);\n"
"border-style: insert;\n"
"border-width: 1px;\n"
"border-radius: 50px;\n"
"border-color: green;\n"
"padding:20px")
        self.countBrowser_1.setObjectName("countBrowser_1")
        self.frame_4 = QtWidgets.QFrame(self.MemorizeScene)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 959, 787))
        self.frame_4.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_4.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_5.raise_()
        self.countBrowser_1.raise_()
        self.stackedWidget.addWidget(self.MemorizeScene)
        self.QuizScene = QtWidgets.QWidget()
        self.QuizScene.setObjectName("QuizScene")
        self.hintEdit = QtWidgets.QLineEdit(self.QuizScene)
        self.hintEdit.setGeometry(QtCore.QRect(90, 500, 500, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hintEdit.setFont(font)
        self.hintEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hintEdit.setStyleSheet("border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(255,255,255,0);\n"
"border-width: 1px;")
        self.hintEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.hintEdit.setReadOnly(True)
        self.hintEdit.setObjectName("hintEdit")
        self.enterEdit = QtWidgets.QLineEdit(self.QuizScene)
        self.enterEdit.setGeometry(QtCore.QRect(90, 620, 500, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enterEdit.setFont(font)
        self.enterEdit.setStyleSheet("border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(255, 170, 255);\n"
"border-width: 1px;")
        self.enterEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enterEdit.setObjectName("enterEdit")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.QuizScene)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(710, 30, 211, 91))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MenuBtn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MenuBtn_2.setFont(font)
        self.MenuBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn_2.setIconSize(QtCore.QSize(40, 40))
        self.MenuBtn_2.setObjectName("MenuBtn_2")
        self.verticalLayout_4.addWidget(self.MenuBtn_2)
        self.wordEnterListWidget = QtWidgets.QListWidget(self.QuizScene)
        self.wordEnterListWidget.setGeometry(QtCore.QRect(690, 180, 251, 501))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.wordEnterListWidget.setFont(font)
        self.wordEnterListWidget.setAlternatingRowColors(True)
        self.wordEnterListWidget.setObjectName("wordEnterListWidget")
        self.remainLabel = QtWidgets.QLabel(self.QuizScene)
        self.remainLabel.setGeometry(QtCore.QRect(690, 130, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remainLabel.setFont(font)
        self.remainLabel.setStyleSheet("border-style: outset;\n"
"border-color: green;\n"
"border-width:1px;\n"
"border-radius: 15px;")
        self.remainLabel.setObjectName("remainLabel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.QuizScene)
        self.groupBox_3.setGeometry(QtCore.QRect(90, 100, 500, 271))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color:blue;\n"
"border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(0,0,0);\n"
"border-width: 1px;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.meaningBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        self.meaningBrowser_2.setGeometry(QtCore.QRect(0, 40, 500, 230))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240, 80))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.meaningBrowser_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meaningBrowser_2.setFont(font)
        self.meaningBrowser_2.setStyleSheet("color: black;\n"
"border-style: outset;\n"
"border-radius:15;\n"
"border-color:black;\n"
"border-width: 1px;")
        self.meaningBrowser_2.setAcceptRichText(True)
        self.meaningBrowser_2.setObjectName("meaningBrowser_2")
        self.showBtn_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.showBtn_2.setGeometry(QtCore.QRect(320, 210, 161, 71))
        self.showBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showBtn_2.setStyleSheet("background-color: rgba(255,255,255,0);\n"
"border-style: outset;\n"
"border-radius:15;\n"
"border-color: rgba(255,255,255,0);\n"
"border-width: 1px;")
        self.showBtn_2.setText("")
        self.showBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.showBtn_2.setObjectName("showBtn_2")
        self.statusBtn = QtWidgets.QToolButton(self.QuizScene)
        self.statusBtn.setGeometry(QtCore.QRect(290, 380, 111, 111))
        self.statusBtn.setStyleSheet("background-color:rgba(255,255,255,0)")
        self.statusBtn.setText("")
        self.statusBtn.setIconSize(QtCore.QSize(100, 100))
        self.statusBtn.setObjectName("statusBtn")
        self.quizLabel = QtWidgets.QLabel(self.QuizScene)
        self.quizLabel.setGeometry(QtCore.QRect(50, 20, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quizLabel.setFont(font)
        self.quizLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quizLabel.setObjectName("quizLabel")
        self.frame_3 = QtWidgets.QFrame(self.QuizScene)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 959, 787))
        self.frame_3.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.raise_()
        self.wordEnterListWidget.raise_()
        self.hintEdit.raise_()
        self.enterEdit.raise_()
        self.horizontalLayoutWidget_6.raise_()
        self.remainLabel.raise_()
        self.groupBox_3.raise_()
        self.statusBtn.raise_()
        self.quizLabel.raise_()
        self.stackedWidget.addWidget(self.QuizScene)
        self.page = QtWidgets.QWidget()
        self.page.setAutoFillBackground(False)
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 959, 787))
        self.frame_2.setStyleSheet("background-color: rgba(240, 240, 240,120)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 1, 2, 1, 1)
        self.lessonListWidget = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lessonListWidget.setFont(font)
        self.lessonListWidget.setAutoFillBackground(True)
        self.lessonListWidget.setStyleSheet("background-color: rgb(231, 231, 231)")
        self.lessonListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lessonListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lessonListWidget.setAlternatingRowColors(True)
        self.lessonListWidget.setObjectName("lessonListWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.lessonListWidget.addItem(item)
        self.gridLayout.addWidget(self.lessonListWidget, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uploadButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.uploadButton.sizePolicy().hasHeightForWidth())
        self.uploadButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.uploadButton.setFont(font)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setMouseTracking(False)
        self.uploadButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uploadButton.setAutoFillBackground(False)
        self.uploadButton.setStyleSheet("background-color:rgb(87, 108, 124);\n"
"    color: white;\n"
"    border-color: green;\n"
"    font: bold 20px;\n"
"    min-width: 10em;")
        self.uploadButton.setIconSize(QtCore.QSize(30, 30))
        self.uploadButton.setCheckable(False)
        self.uploadButton.setAutoDefault(False)
        self.uploadButton.setDefault(True)
        self.uploadButton.setFlat(False)
        self.uploadButton.setObjectName("uploadButton")
        self.verticalLayout_2.addWidget(self.uploadButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 16)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bookListWidget.setToolTip(_translate("MainWindow", "BookList"))
        self.bookListWidget.setSortingEnabled(False)
        self.progressLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:normal;\">上次学习进度： SAT Vocabularies, Lesson 1, 共学习 ———— 词</span></p></body></html>"))
        self.WordLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#834100;\">单词</span></p></body></html>"))
        self.MeaningLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">词义</span></p></body></html>"))
        self.MemorizeBtn_0.setText(_translate("MainWindow", "背单词"))
        self.QuizBtn_0.setText(_translate("MainWindow", "小测"))
        self.groupBox.setTitle(_translate("MainWindow", "单词"))
        self.wordBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:italic;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-weight:400; font-style:normal;\"><br /></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "词义"))
        self.meaningBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-style:italic;\"><br /></p></body></html>"))
        self.MenuBtn_1.setText(_translate("MainWindow", "主页"))
        self.QuizBtn_1.setText(_translate("MainWindow", "小测"))
        self.countBrowser_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:48pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:48px;\"><br /></p></body></html>"))
        self.MenuBtn_2.setText(_translate("MainWindow", "主页"))
        self.remainLabel.setText(_translate("MainWindow", "剩余:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "词义"))
        self.meaningBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-style:italic;\"><br /></p></body></html>"))
        self.quizLabel.setText(_translate("MainWindow", "Tmp"))
        __sortingEnabled = self.lessonListWidget.isSortingEnabled()
        self.lessonListWidget.setSortingEnabled(False)
        item = self.lessonListWidget.item(0)
        item.setText(_translate("MainWindow", " 请"))
        item = self.lessonListWidget.item(1)
        item.setText(_translate("MainWindow", " 先"))
        item = self.lessonListWidget.item(2)
        item.setText(_translate("MainWindow", " 选"))
        item = self.lessonListWidget.item(3)
        item.setText(_translate("MainWindow", " 择"))
        item = self.lessonListWidget.item(4)
        item.setText(_translate("MainWindow", " 一"))
        item = self.lessonListWidget.item(5)
        item.setText(_translate("MainWindow", " 本"))
        item = self.lessonListWidget.item(6)
        item.setText(_translate("MainWindow", " 书"))
        self.lessonListWidget.setSortingEnabled(__sortingEnabled)
        self.uploadButton.setText(_translate("MainWindow", "上传Excel文档"))
        self.uploadButton.setShortcut(_translate("MainWindow", "Ctrl+U"))
