# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_Chinese_Adjust.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1159, 828)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TitleBar_Widget = QtWidgets.QWidget(self.centralwidget)
        self.TitleBar_Widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleBar_Widget.sizePolicy().hasHeightForWidth())
        self.TitleBar_Widget.setSizePolicy(sizePolicy)
        self.TitleBar_Widget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.TitleBar_Widget.setAutoFillBackground(False)
        self.TitleBar_Widget.setStyleSheet("")
        self.TitleBar_Widget.setObjectName("TitleBar_Widget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.TitleBar_Widget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.exitBtn = QtWidgets.QToolButton(self.TitleBar_Widget)
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setStyleSheet("background-color: rgb(255,255,255,0)\n"
"")
        self.exitBtn.setText("")
        self.exitBtn.setIconSize(QtCore.QSize(20, 20))
        self.exitBtn.setObjectName("exitBtn")
        self.gridLayout_8.addWidget(self.exitBtn, 0, 3, 2, 1)
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setContentsMargins(5, -1, -1, -1)
        self.gridLayout_29.setHorizontalSpacing(5)
        self.gridLayout_29.setVerticalSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.updateCheckBtn = QtWidgets.QPushButton(self.TitleBar_Widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.updateCheckBtn.setFont(font)
        self.updateCheckBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.updateCheckBtn.setStyleSheet("background-color:rgb(50, 60, 71);\n"
"color:white;")
        self.updateCheckBtn.setObjectName("updateCheckBtn")
        self.gridLayout_29.addWidget(self.updateCheckBtn, 0, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem, 0, 7, 1, 1)
        self.useTipBtn = QtWidgets.QPushButton(self.TitleBar_Widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.useTipBtn.setFont(font)
        self.useTipBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.useTipBtn.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.useTipBtn.setStyleSheet("background-color:rgb(50, 60, 71);\n"
"color:white;")
        self.useTipBtn.setObjectName("useTipBtn")
        self.gridLayout_29.addWidget(self.useTipBtn, 0, 6, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_29, 1, 1, 1, 1)
        self.miniBtn = QtWidgets.QToolButton(self.TitleBar_Widget)
        self.miniBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.miniBtn.setStyleSheet("background-color: rgb(255,255,255,0)\n"
"")
        self.miniBtn.setText("")
        self.miniBtn.setIconSize(QtCore.QSize(20, 20))
        self.miniBtn.setObjectName("miniBtn")
        self.gridLayout_8.addWidget(self.miniBtn, 0, 2, 2, 1)
        self.TitleBar_Label = QtWidgets.QLabel(self.TitleBar_Widget)
        self.TitleBar_Label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleBar_Label.sizePolicy().hasHeightForWidth())
        self.TitleBar_Label.setSizePolicy(sizePolicy)
        self.TitleBar_Label.setStyleSheet("")
        self.TitleBar_Label.setObjectName("TitleBar_Label")
        self.gridLayout_8.addWidget(self.TitleBar_Label, 0, 1, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.pushButton = QtWidgets.QPushButton(self.TitleBar_Widget)
        self.pushButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:rgb(50, 60, 71);\n"
"color:white;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_27.addWidget(self.pushButton, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_27, 1, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.icoBtn = QtWidgets.QToolButton(self.TitleBar_Widget)
        self.icoBtn.setStyleSheet("background-color:transparent")
        self.icoBtn.setText("")
        self.icoBtn.setObjectName("icoBtn")
        self.horizontalLayout_11.addWidget(self.icoBtn)
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem1)
        self.gridLayout_8.addLayout(self.horizontalLayout_11, 0, 0, 1, 1)
        self.gridLayout_8.setRowStretch(0, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.TitleBar_Widget, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 3)
        self.lessonListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lessonListWidget.sizePolicy().hasHeightForWidth())
        self.lessonListWidget.setSizePolicy(sizePolicy)
        self.lessonListWidget.setMinimumSize(QtCore.QSize(110, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lessonListWidget.setFont(font)
        self.lessonListWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lessonListWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lessonListWidget.setAutoFillBackground(True)
        self.lessonListWidget.setStyleSheet("background-color:rgb(252, 252, 252)")
        self.lessonListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lessonListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lessonListWidget.setAlternatingRowColors(True)
        self.lessonListWidget.setObjectName("lessonListWidget")
        self.gridLayout.addWidget(self.lessonListWidget, 2, 1, 5, 1)
        self.bookListWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bookListWidget.sizePolicy().hasHeightForWidth())
        self.bookListWidget.setSizePolicy(sizePolicy)
        self.bookListWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.bookListWidget.setToolTipDuration(-1)
        self.bookListWidget.setAutoFillBackground(True)
        self.bookListWidget.setStyleSheet("font: 75 12pt \"Times New Roman\";\n"
"font-style: bold;\n"
"color:rgb(255, 255, 255);\n"
"background: rgb(42, 51, 60)\n"
"")
        self.bookListWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bookListWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bookListWidget.setAlternatingRowColors(False)
        self.bookListWidget.setProperty("isWrapping", False)
        self.bookListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.bookListWidget.setWordWrap(True)
        self.bookListWidget.setObjectName("bookListWidget")
        self.gridLayout.addWidget(self.bookListWidget, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.downloadBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.downloadBtn.sizePolicy().hasHeightForWidth())
        self.downloadBtn.setSizePolicy(sizePolicy)
        self.downloadBtn.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.downloadBtn.setFont(font)
        self.downloadBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadBtn.setMouseTracking(False)
        self.downloadBtn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.downloadBtn.setAutoFillBackground(False)
        self.downloadBtn.setStyleSheet("background-color:rgb(204, 255, 153);\n"
"    color: black;\n"
"    font: bold 20px;\n"
"")
        self.downloadBtn.setIconSize(QtCore.QSize(30, 30))
        self.downloadBtn.setCheckable(False)
        self.downloadBtn.setAutoDefault(False)
        self.downloadBtn.setDefault(True)
        self.downloadBtn.setFlat(False)
        self.downloadBtn.setObjectName("downloadBtn")
        self.horizontalLayout_12.addWidget(self.downloadBtn)
        self.uploadButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uploadButton.sizePolicy().hasHeightForWidth())
        self.uploadButton.setSizePolicy(sizePolicy)
        self.uploadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.uploadButton.setStyleSheet("background-color:rgb(230, 255, 255);\n"
"    color: black;\n"
"    font: bold 20px;\n"
"")
        self.uploadButton.setObjectName("uploadButton")
        self.horizontalLayout_12.addWidget(self.uploadButton)
        self.horizontalLayout_12.setStretch(0, 3)
        self.horizontalLayout_12.setStretch(1, 2)
        self.gridLayout.addLayout(self.horizontalLayout_12, 1, 0, 1, 2)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_9.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.progressLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressLabel.sizePolicy().hasHeightForWidth())
        self.progressLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.progressLabel.setFont(font)
        self.progressLabel.setStyleSheet("")
        self.progressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.progressLabel.setObjectName("progressLabel")
        self.gridLayout_9.addWidget(self.progressLabel, 0, 0, 1, 1)
        self.helpBtn = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpBtn.sizePolicy().hasHeightForWidth())
        self.helpBtn.setSizePolicy(sizePolicy)
        self.helpBtn.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.helpBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.helpBtn.setText("")
        self.helpBtn.setIconSize(QtCore.QSize(40, 40))
        self.helpBtn.setObjectName("helpBtn")
        self.gridLayout_9.addWidget(self.helpBtn, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 1, 2, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 5, 0, 1, 1)
        self.addBookBtn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBookBtn.sizePolicy().hasHeightForWidth())
        self.addBookBtn.setSizePolicy(sizePolicy)
        self.addBookBtn.setMinimumSize(QtCore.QSize(0, 0))
        self.addBookBtn.setBaseSize(QtCore.QSize(0, 19))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addBookBtn.setFont(font)
        self.addBookBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBookBtn.setStyleSheet("background-color: rgb(27, 33, 39);\n"
"color: white;")
        self.addBookBtn.setIconSize(QtCore.QSize(30, 30))
        self.addBookBtn.setObjectName("addBookBtn")
        self.gridLayout.addWidget(self.addBookBtn, 3, 0, 2, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setTabletTracking(False)
        self.stackedWidget.setStyleSheet("background-color: rgba(255,255,255,50);")
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.OverviewScene = QtWidgets.QWidget()
        self.OverviewScene.setAutoFillBackground(False)
        self.OverviewScene.setObjectName("OverviewScene")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.OverviewScene)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(50, 0, 50, -1)
        self.horizontalLayout_3.setSpacing(50)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.WordLabel_0 = QtWidgets.QLabel(self.OverviewScene)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.WordLabel_0.setFont(font)
        self.WordLabel_0.setObjectName("WordLabel_0")
        self.horizontalLayout_3.addWidget(self.WordLabel_0)
        self.MeaningLabel_0 = QtWidgets.QLabel(self.OverviewScene)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.MeaningLabel_0.setFont(font)
        self.MeaningLabel_0.setObjectName("MeaningLabel_0")
        self.horizontalLayout_3.addWidget(self.MeaningLabel_0)
        self.gridLayout_13.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(50, 0, 50, 50)
        self.horizontalLayout_2.setSpacing(50)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.wordListWidget = QtWidgets.QListWidget(self.OverviewScene)
        self.wordListWidget.setStyleSheet("    font: 20px;\n"
"    font-style: bold;\n"
"    font-style: italic;\n"
"    background-color: rgba(255,255,255,200)")
        self.wordListWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.wordListWidget.setProperty("showDropIndicator", False)
        self.wordListWidget.setAlternatingRowColors(True)
        self.wordListWidget.setWordWrap(False)
        self.wordListWidget.setObjectName("wordListWidget")
        self.horizontalLayout_2.addWidget(self.wordListWidget)
        self.meaningListWidget = QtWidgets.QListWidget(self.OverviewScene)
        self.meaningListWidget.setStyleSheet("    font: 20px;\n"
"    font-style: bold;\n"
"    background-color: rgba(255,255,255,200)")
        self.meaningListWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.meaningListWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.meaningListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.meaningListWidget.setAutoScroll(True)
        self.meaningListWidget.setProperty("showDropIndicator", True)
        self.meaningListWidget.setAlternatingRowColors(True)
        self.meaningListWidget.setObjectName("meaningListWidget")
        self.horizontalLayout_2.addWidget(self.meaningListWidget)
        self.gridLayout_13.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, 30, -1)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.MemorizeBtn_0 = QtWidgets.QPushButton(self.OverviewScene)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MemorizeBtn_0.setFont(font)
        self.MemorizeBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MemorizeBtn_0.setStyleSheet("    color:brown;\n"
"    border-color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255,255,255)")
        self.MemorizeBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.MemorizeBtn_0.setObjectName("MemorizeBtn_0")
        self.verticalLayout.addWidget(self.MemorizeBtn_0)
        spacerItem3 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.QuizBtn_0 = QtWidgets.QPushButton(self.OverviewScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_0.sizePolicy().hasHeightForWidth())
        self.QuizBtn_0.setSizePolicy(sizePolicy)
        self.QuizBtn_0.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuizBtn_0.setFont(font)
        self.QuizBtn_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_0.setStyleSheet("    color:brown;\n"
"    border-color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255,255,255)")
        self.QuizBtn_0.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_0.setObjectName("QuizBtn_0")
        self.verticalLayout.addWidget(self.QuizBtn_0)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.gridLayout_13.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout_13.setColumnStretch(0, 3)
        self.gridLayout_13.setColumnStretch(1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.OverviewScene)
        self.MemorizeScene = QtWidgets.QWidget()
        self.MemorizeScene.setAutoFillBackground(False)
        self.MemorizeScene.setStyleSheet("")
        self.MemorizeScene.setObjectName("MemorizeScene")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.MemorizeScene)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 20, -1, 30)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 60, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.backBtn = QtWidgets.QPushButton(self.MemorizeScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setMinimumSize(QtCore.QSize(20, 10))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.backBtn.setFont(font)
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.backBtn.setText("")
        self.backBtn.setIconSize(QtCore.QSize(100, 100))
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout.addWidget(self.backBtn)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.translateBtn = QtWidgets.QPushButton(self.MemorizeScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateBtn.sizePolicy().hasHeightForWidth())
        self.translateBtn.setSizePolicy(sizePolicy)
        self.translateBtn.setMinimumSize(QtCore.QSize(20, 5))
        self.translateBtn.setBaseSize(QtCore.QSize(20, 10))
        self.translateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.translateBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.translateBtn.setText("")
        self.translateBtn.setIconSize(QtCore.QSize(100, 100))
        self.translateBtn.setObjectName("translateBtn")
        self.horizontalLayout.addWidget(self.translateBtn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.NextBtn = QtWidgets.QPushButton(self.MemorizeScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextBtn.sizePolicy().hasHeightForWidth())
        self.NextBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.NextBtn.setFont(font)
        self.NextBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NextBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.NextBtn.setText("")
        self.NextBtn.setIconSize(QtCore.QSize(100, 100))
        self.NextBtn.setObjectName("NextBtn")
        self.horizontalLayout.addWidget(self.NextBtn)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(4, 2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 6, 0, 1, 5)
        self.wordBox = QtWidgets.QWidget(self.MemorizeScene)
        self.wordBox.setMinimumSize(QtCore.QSize(383, 120))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.wordBox.setFont(font)
        self.wordBox.setAutoFillBackground(False)
        self.wordBox.setStyleSheet("color: blue;")
        self.wordBox.setObjectName("wordBox")
        self.wordBrowser = QtWidgets.QTextBrowser(self.wordBox)
        self.wordBrowser.setGeometry(QtCore.QRect(20, 46, 401, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wordBrowser.sizePolicy().hasHeightForWidth())
        self.wordBrowser.setSizePolicy(sizePolicy)
        self.wordBrowser.setMaximumSize(QtCore.QSize(16777215, 55))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.wordBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.wordBrowser.setFont(font)
        self.wordBrowser.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:black;")
        self.wordBrowser.setObjectName("wordBrowser")
        self.layoutWidget = QtWidgets.QWidget(self.wordBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 401, 44))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.tag_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.tag_1.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tag_1.setFont(font)
        self.tag_1.setStyleSheet("background-color:transparent;\n"
"color:black;\n"
"font-size:15px;\n"
"font-style:bold;")
        self.tag_1.setText("")
        self.tag_1.setObjectName("tag_1")
        self.horizontalLayout_5.addWidget(self.tag_1)
        self.tag_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.tag_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tag_2.setFont(font)
        self.tag_2.setStyleSheet("background-color:transparent;\n"
"color:black;\n"
"font-size:15px;\n"
"font-style:bold;")
        self.tag_2.setText("")
        self.tag_2.setObjectName("tag_2")
        self.horizontalLayout_5.addWidget(self.tag_2)
        self.tag_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.tag_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tag_3.setFont(font)
        self.tag_3.setStyleSheet("background-color:transparent;\n"
"color:black;\n"
"font-size:15px;\n"
"font-style:bold;")
        self.tag_3.setText("")
        self.tag_3.setObjectName("tag_3")
        self.horizontalLayout_5.addWidget(self.tag_3)
        self.tag_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.tag_4.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.tag_4.setFont(font)
        self.tag_4.setStyleSheet("background-color:transparent;\n"
"color:black;\n"
"font-size:15px;\n"
"font-style:bold;")
        self.tag_4.setText("")
        self.tag_4.setObjectName("tag_4")
        self.horizontalLayout_5.addWidget(self.tag_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.wordBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 103, 401, 43))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.starBtn_2 = QtWidgets.QToolButton(self.layoutWidget1)
        self.starBtn_2.setStyleSheet("background-color:transparent;")
        self.starBtn_2.setText("")
        self.starBtn_2.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_2.setObjectName("starBtn_2")
        self.horizontalLayout_4.addWidget(self.starBtn_2)
        self.starBtn_1 = QtWidgets.QToolButton(self.layoutWidget1)
        self.starBtn_1.setStyleSheet("background-color:transparent;")
        self.starBtn_1.setText("")
        self.starBtn_1.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_1.setObjectName("starBtn_1")
        self.horizontalLayout_4.addWidget(self.starBtn_1)
        self.starBtn_3 = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starBtn_3.sizePolicy().hasHeightForWidth())
        self.starBtn_3.setSizePolicy(sizePolicy)
        self.starBtn_3.setStyleSheet("background-color:transparent;")
        self.starBtn_3.setText("")
        self.starBtn_3.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_3.setObjectName("starBtn_3")
        self.horizontalLayout_4.addWidget(self.starBtn_3)
        self.starBtn_4 = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.starBtn_4.sizePolicy().hasHeightForWidth())
        self.starBtn_4.setSizePolicy(sizePolicy)
        self.starBtn_4.setMinimumSize(QtCore.QSize(30, 30))
        self.starBtn_4.setStyleSheet("background-color:transparent;")
        self.starBtn_4.setText("")
        self.starBtn_4.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_4.setObjectName("starBtn_4")
        self.horizontalLayout_4.addWidget(self.starBtn_4)
        self.starBtn_5 = QtWidgets.QToolButton(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.starBtn_5.sizePolicy().hasHeightForWidth())
        self.starBtn_5.setSizePolicy(sizePolicy)
        self.starBtn_5.setStyleSheet("background-color:transparent;")
        self.starBtn_5.setText("")
        self.starBtn_5.setIconSize(QtCore.QSize(30, 30))
        self.starBtn_5.setObjectName("starBtn_5")
        self.horizontalLayout_4.addWidget(self.starBtn_5)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.wordBox, 0, 1, 3, 3)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 4, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MenuBtn_1 = QtWidgets.QPushButton(self.MemorizeScene)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MenuBtn_1.setFont(font)
        self.MenuBtn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn_1.setStyleSheet("    color:brown;\n"
"    border-color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255,255,255)")
        self.MenuBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.MenuBtn_1.setObjectName("MenuBtn_1")
        self.verticalLayout_3.addWidget(self.MenuBtn_1)
        self.QuizBtn_1 = QtWidgets.QPushButton(self.MemorizeScene)
        self.QuizBtn_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.QuizBtn_1.sizePolicy().hasHeightForWidth())
        self.QuizBtn_1.setSizePolicy(sizePolicy)
        self.QuizBtn_1.setMinimumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.QuizBtn_1.setFont(font)
        self.QuizBtn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.QuizBtn_1.setStyleSheet("    color:brown;\n"
"    border-color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255,255,255)")
        self.QuizBtn_1.setIconSize(QtCore.QSize(40, 40))
        self.QuizBtn_1.setObjectName("QuizBtn_1")
        self.verticalLayout_3.addWidget(self.QuizBtn_1)
        self.picWidget = QtWidgets.QWidget(self.MemorizeScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picWidget.sizePolicy().hasHeightForWidth())
        self.picWidget.setSizePolicy(sizePolicy)
        self.picWidget.setMinimumSize(QtCore.QSize(219, 283))
        self.picWidget.setMaximumSize(QtCore.QSize(219, 283))
        self.picWidget.setObjectName("picWidget")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.picWidget)
        self.gridLayout_28.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.exchangeBox = QtWidgets.QGroupBox(self.picWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeBox.setFont(font)
        self.exchangeBox.setStyleSheet("color:brown;")
        self.exchangeBox.setObjectName("exchangeBox")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.exchangeBox)
        self.gridLayout_32.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.exchangeEdit = QtWidgets.QTextEdit(self.exchangeBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.exchangeEdit.setFont(font)
        self.exchangeEdit.setStyleSheet("color:black;\n"
"background: rgba(255,255,255,100);")
        self.exchangeEdit.setReadOnly(True)
        self.exchangeEdit.setObjectName("exchangeEdit")
        self.gridLayout_32.addWidget(self.exchangeEdit, 0, 0, 1, 1)
        self.gridLayout_28.addWidget(self.exchangeBox, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.picWidget)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 4, 4, 1)
        self.PreSufBox = QtWidgets.QWidget(self.MemorizeScene)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.PreSufBox.setFont(font)
        self.PreSufBox.setStyleSheet("color: blue;")
        self.PreSufBox.setObjectName("PreSufBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.PreSufBox)
        self.gridLayout_7.setContentsMargins(19, 14, 10, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.PreSufBrowser = QtWidgets.QTextEdit(self.PreSufBox)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.PreSufBrowser.setFont(font)
        self.PreSufBrowser.setStyleSheet("color:black;\n"
"background: rgba(255,255,255,100);")
        self.PreSufBrowser.setReadOnly(True)
        self.PreSufBrowser.setObjectName("PreSufBrowser")
        self.gridLayout_7.addWidget(self.PreSufBrowser, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.PreSufBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.PreSufBox, 3, 0, 2, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 60, 10)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.showBtn = QtWidgets.QPushButton(self.MemorizeScene)
        self.showBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showBtn.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.showBtn.setText("")
        self.showBtn.setIconSize(QtCore.QSize(50, 50))
        self.showBtn.setObjectName("showBtn")
        self.horizontalLayout_7.addWidget(self.showBtn)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.horizontalLayout_7, 5, 0, 1, 5)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setContentsMargins(-1, 20, -1, 0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.countBrowser_1 = QtWidgets.QTextBrowser(self.MemorizeScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBrowser_1.sizePolicy().hasHeightForWidth())
        self.countBrowser_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.countBrowser_1.setFont(font)
        self.countBrowser_1.setStyleSheet("background-color:rgba(227, 227, 227,100);\n"
"border-style: insert;\n"
"border-width: 20px;\n"
"border-radius: 50px;\n"
"")
        self.countBrowser_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.countBrowser_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.countBrowser_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.countBrowser_1.setObjectName("countBrowser_1")
        self.gridLayout_24.addWidget(self.countBrowser_1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout_4.addLayout(self.gridLayout_24, 0, 0, 3, 1)
        self.widget_2 = QtWidgets.QWidget(self.MemorizeScene)
        self.widget_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("color:blue;")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.meaningBrowser = QtWidgets.QTextBrowser(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meaningBrowser.sizePolicy().hasHeightForWidth())
        self.meaningBrowser.setSizePolicy(sizePolicy)
        self.meaningBrowser.setMinimumSize(QtCore.QSize(0, 10))
        self.meaningBrowser.setBaseSize(QtCore.QSize(0, 180))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.meaningBrowser.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meaningBrowser.setFont(font)
        self.meaningBrowser.setStyleSheet("background-color:rgba(255, 255, 255,150);\n"
"color: black；\n"
"")
        self.meaningBrowser.setFrameShadow(QtWidgets.QFrame.Raised)
        self.meaningBrowser.setAcceptRichText(True)
        self.meaningBrowser.setObjectName("meaningBrowser")
        self.gridLayout_6.addWidget(self.meaningBrowser, 1, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ChineseBtn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ChineseBtn.sizePolicy().hasHeightForWidth())
        self.ChineseBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.ChineseBtn.setFont(font)
        self.ChineseBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ChineseBtn.setStyleSheet("background-color:rgb(226, 255, 255)")
        self.ChineseBtn.setCheckable(True)
        self.ChineseBtn.setAutoRepeat(False)
        self.ChineseBtn.setAutoExclusive(True)
        self.ChineseBtn.setFlat(True)
        self.ChineseBtn.setObjectName("ChineseBtn")
        self.horizontalLayout_6.addWidget(self.ChineseBtn)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_6.addWidget(self.line)
        self.EnglishBtn = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnglishBtn.sizePolicy().hasHeightForWidth())
        self.EnglishBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.EnglishBtn.setFont(font)
        self.EnglishBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EnglishBtn.setAutoFillBackground(False)
        self.EnglishBtn.setStyleSheet("background-color:rgb(246, 237, 255)")
        self.EnglishBtn.setCheckable(True)
        self.EnglishBtn.setAutoRepeat(False)
        self.EnglishBtn.setAutoExclusive(True)
        self.EnglishBtn.setFlat(True)
        self.EnglishBtn.setObjectName("EnglishBtn")
        self.horizontalLayout_6.addWidget(self.EnglishBtn)
        self.proUSBtn = QtWidgets.QToolButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proUSBtn.sizePolicy().hasHeightForWidth())
        self.proUSBtn.setSizePolicy(sizePolicy)
        self.proUSBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proUSBtn.setStyleSheet("background-color: transparent;")
        self.proUSBtn.setText("")
        self.proUSBtn.setIconSize(QtCore.QSize(40, 40))
        self.proUSBtn.setObjectName("proUSBtn")
        self.horizontalLayout_6.addWidget(self.proUSBtn)
        self.proENGBtn = QtWidgets.QToolButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proENGBtn.sizePolicy().hasHeightForWidth())
        self.proENGBtn.setSizePolicy(sizePolicy)
        self.proENGBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proENGBtn.setStyleSheet("background-color: transparent;")
        self.proENGBtn.setText("")
        self.proENGBtn.setIconSize(QtCore.QSize(40, 40))
        self.proENGBtn.setObjectName("proENGBtn")
        self.horizontalLayout_6.addWidget(self.proENGBtn)
        self.gridLayout_6.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_2, 3, 1, 2, 3)
        self.gridLayout_4.setColumnStretch(0, 4)
        self.gridLayout_4.setColumnStretch(1, 5)
        self.gridLayout_4.setColumnStretch(2, 2)
        self.gridLayout_4.setColumnStretch(3, 2)
        self.gridLayout_4.setColumnStretch(4, 5)
        self.gridLayout_4.setRowStretch(0, 1)
        self.gridLayout_4.setRowStretch(1, 1)
        self.gridLayout_4.setRowStretch(2, 1)
        self.gridLayout_4.setRowStretch(3, 10)
        self.gridLayout_4.setRowStretch(4, 2)
        self.gridLayout_4.setRowStretch(5, 3)
        self.gridLayout_4.setRowStretch(6, 3)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.MemorizeScene)
        self.QuizScene = QtWidgets.QWidget()
        self.QuizScene.setObjectName("QuizScene")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.QuizScene)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(40, 20, 40, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem10)
        self.quizLabel = QtWidgets.QLabel(self.QuizScene)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quizLabel.setFont(font)
        self.quizLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.quizLabel.setObjectName("quizLabel")
        self.verticalLayout_7.addWidget(self.quizLabel)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem11)
        self.groupBox_3 = QtWidgets.QGroupBox(self.QuizScene)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setItalic(False)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setStyleSheet("color:blue;\n"
"border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(0,0,0);\n"
"border-width: 1px;")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_25.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.meaningBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meaningBrowser_2.sizePolicy().hasHeightForWidth())
        self.meaningBrowser_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.meaningBrowser_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.meaningBrowser_2.setFont(font)
        self.meaningBrowser_2.setStyleSheet("color: black;\n"
"border-style: insert;\n"
"border-radius:15;\n"
"border-color:black;\n"
"border-width: 1px;")
        self.meaningBrowser_2.setAcceptRichText(True)
        self.meaningBrowser_2.setObjectName("meaningBrowser_2")
        self.gridLayout_25.addWidget(self.meaningBrowser_2, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem12)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.proUSBtn_2 = QtWidgets.QToolButton(self.QuizScene)
        self.proUSBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proUSBtn_2.setStyleSheet("background-color: transparent;")
        self.proUSBtn_2.setText("")
        self.proUSBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.proUSBtn_2.setObjectName("proUSBtn_2")
        self.horizontalLayout_8.addWidget(self.proUSBtn_2)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem14)
        self.statusBtn = QtWidgets.QToolButton(self.QuizScene)
        self.statusBtn.setStyleSheet("background-color:rgba(255,255,255,0)")
        self.statusBtn.setText("")
        self.statusBtn.setIconSize(QtCore.QSize(100, 100))
        self.statusBtn.setObjectName("statusBtn")
        self.horizontalLayout_8.addWidget(self.statusBtn)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.proENGBtn_2 = QtWidgets.QToolButton(self.QuizScene)
        self.proENGBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.proENGBtn_2.setStyleSheet("background-color: transparent;")
        self.proENGBtn_2.setText("")
        self.proENGBtn_2.setIconSize(QtCore.QSize(50, 50))
        self.proENGBtn_2.setObjectName("proENGBtn_2")
        self.horizontalLayout_8.addWidget(self.proENGBtn_2)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setContentsMargins(50, -1, 50, -1)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.hintEdit = QtWidgets.QLineEdit(self.QuizScene)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hintEdit.setFont(font)
        self.hintEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hintEdit.setStyleSheet("border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(255,255,255,0);\n"
"border-width: 1px;")
        self.hintEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.hintEdit.setReadOnly(True)
        self.hintEdit.setObjectName("hintEdit")
        self.gridLayout_20.addWidget(self.hintEdit, 0, 0, 1, 1)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.translateBtn_2 = QtWidgets.QPushButton(self.QuizScene)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.translateBtn_2.sizePolicy().hasHeightForWidth())
        self.translateBtn_2.setSizePolicy(sizePolicy)
        self.translateBtn_2.setMinimumSize(QtCore.QSize(20, 5))
        self.translateBtn_2.setBaseSize(QtCore.QSize(20, 10))
        self.translateBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.translateBtn_2.setStyleSheet("background-color: rgba(255,255,255,0)")
        self.translateBtn_2.setText("")
        self.translateBtn_2.setIconSize(QtCore.QSize(100, 100))
        self.translateBtn_2.setObjectName("translateBtn_2")
        self.horizontalLayout_10.addWidget(self.translateBtn_2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem18)
        self.gridLayout_22.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_22, 1, 0, 1, 1)
        self.enterEdit = QtWidgets.QLineEdit(self.QuizScene)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.enterEdit.setFont(font)
        self.enterEdit.setStyleSheet("border-style: outset;\n"
"border-radius:15;\n"
"border-color:rgb(255, 170, 255);\n"
"border-width: 1px;")
        self.enterEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.enterEdit.setObjectName("enterEdit")
        self.gridLayout_20.addWidget(self.enterEdit, 2, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_20.addItem(spacerItem19, 3, 0, 1, 1)
        self.gridLayout_20.setRowStretch(0, 1)
        self.gridLayout_20.setRowStretch(1, 1)
        self.gridLayout_20.setRowStretch(2, 1)
        self.gridLayout_20.setRowStretch(3, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_20)
        self.verticalLayout_8.setStretch(0, 4)
        self.verticalLayout_8.setStretch(1, 1)
        self.verticalLayout_8.setStretch(2, 4)
        self.gridLayout_23.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(20, 100, 20, 0)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.MenuBtn_2 = QtWidgets.QPushButton(self.QuizScene)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MenuBtn_2.setFont(font)
        self.MenuBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MenuBtn_2.setStyleSheet("    color:brown;\n"
"    border-color: black;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255,255,255)")
        self.MenuBtn_2.setIconSize(QtCore.QSize(40, 40))
        self.MenuBtn_2.setObjectName("MenuBtn_2")
        self.verticalLayout_4.addWidget(self.MenuBtn_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.remainLabel = QtWidgets.QLabel(self.QuizScene)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.remainLabel.setFont(font)
        self.remainLabel.setStyleSheet("border-style: outset;\n"
"border-color: green;\n"
"border-width:1px;\n"
"border-radius: 15px;")
        self.remainLabel.setObjectName("remainLabel")
        self.verticalLayout_5.addWidget(self.remainLabel)
        self.wordEnterListWidget = QtWidgets.QListWidget(self.QuizScene)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.wordEnterListWidget.setFont(font)
        self.wordEnterListWidget.setStyleSheet("background-color: rgba(255, 255, 255, 150)")
        self.wordEnterListWidget.setAlternatingRowColors(True)
        self.wordEnterListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.wordEnterListWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.wordEnterListWidget.setUniformItemSizes(False)
        self.wordEnterListWidget.setObjectName("wordEnterListWidget")
        self.verticalLayout_5.addWidget(self.wordEnterListWidget)
        spacerItem20 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem20)
        self.gridLayout_23.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_23.setColumnStretch(0, 2)
        self.gridLayout_23.setColumnStretch(1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.QuizScene)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setContentsMargins(100, 100, 100, 100)
        self.gridLayout_30.setVerticalSpacing(100)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.greatSentenceCHI = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.greatSentenceCHI.setFont(font)
        self.greatSentenceCHI.setStyleSheet("color:rgb(85, 0, 0)")
        self.greatSentenceCHI.setWordWrap(True)
        self.greatSentenceCHI.setObjectName("greatSentenceCHI")
        self.gridLayout_30.addWidget(self.greatSentenceCHI, 1, 0, 1, 1)
        self.greatSentenceEng = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.greatSentenceEng.setFont(font)
        self.greatSentenceEng.setWordWrap(True)
        self.greatSentenceEng.setObjectName("greatSentenceEng")
        self.gridLayout_30.addWidget(self.greatSentenceEng, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_30.addItem(spacerItem21, 2, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_30, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page = QtWidgets.QWidget()
        self.page.setAutoFillBackground(False)
        self.page.setStyleSheet("")
        self.page.setObjectName("page")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setContentsMargins(-1, 30, -1, -1)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setEnabled(False)
        self.label_5.setObjectName("label_5")
        self.gridLayout_15.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.gridLayout_15.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setEnabled(False)
        self.label_8.setObjectName("label_8")
        self.gridLayout_15.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 2, 2, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.page)
        self.toolButton_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_4.setFont(font)
        self.toolButton_4.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_15.addWidget(self.toolButton_4, 1, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.page)
        self.toolButton_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setStyleSheet("\n"
"color: blue;\n"
"background-color: rgba(164, 255, 195, 0)")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_15.addWidget(self.toolButton_3, 1, 3, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.page)
        self.toolButton_7.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_7.setFont(font)
        self.toolButton_7.setStyleSheet("\n"
"color: blue;\n"
"background-color: rgba(164, 255, 195, 0)")
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout_15.addWidget(self.toolButton_7, 2, 3, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.page)
        self.toolButton_6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_6.setFont(font)
        self.toolButton_6.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout_15.addWidget(self.toolButton_6, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_15.addWidget(self.label_7, 1, 2, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.page)
        self.toolButton_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_15.addWidget(self.toolButton_2, 0, 1, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.page)
        self.toolButton_5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton_5.setFont(font)
        self.toolButton_5.setStyleSheet("background-color: rgba(164, 255, 195, 0);\n"
"color: blue;")
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_15.addWidget(self.toolButton_5, 0, 3, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem22, 3, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_15, 1, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.page)
        self.textEdit.setEnabled(False)
        self.textEdit.setStyleSheet("background-color: rgb(255,255,255,0);\n"
"border-style: insert")
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout_18.addWidget(self.textEdit, 0, 0, 1, 3)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_18.addLayout(self.gridLayout_16, 1, 0, 1, 1)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_18.addLayout(self.gridLayout_17, 1, 2, 1, 1)
        self.gridLayout_18.setRowStretch(0, 2)
        self.gridLayout_18.setRowStretch(1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.gridLayout.addWidget(self.stackedWidget, 2, 2, 5, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 16)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 60)
        self.gridLayout.setRowStretch(4, 4)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 2, 2)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exitBtn.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.updateCheckBtn.setText(_translate("MainWindow", "检查更新"))
        self.useTipBtn.setText(_translate("MainWindow", "使用技巧"))
        self.miniBtn.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.TitleBar_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; font-style:italic; color:#ffffff;\">RemV</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "登录"))
        self.lessonListWidget.setToolTip(_translate("MainWindow", "选课列表"))
        self.bookListWidget.setSortingEnabled(False)
        self.downloadBtn.setText(_translate("MainWindow", "获取单词书"))
        self.downloadBtn.setShortcut(_translate("MainWindow", "Ctrl+D"))
        self.uploadButton.setText(_translate("MainWindow", "上传"))
        self.uploadButton.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.progressLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-style:normal;\">上次学习进度： SAT Vocabularies, Lesson 1, 共学习 ———— 词</span></p></body></html>"))
        self.addBookBtn.setText(_translate("MainWindow", "快速录入错词"))
        self.WordLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#834100;\">单词</span></p></body></html>"))
        self.MeaningLabel_0.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#00aaff;\">词义</span></p></body></html>"))
        self.MemorizeBtn_0.setText(_translate("MainWindow", "背单词"))
        self.QuizBtn_0.setText(_translate("MainWindow", "小测"))
        self.wordBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:italic;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-weight:400; font-style:normal;\"><br /></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt;\">单词</span></p></body></html>"))
        self.MenuBtn_1.setText(_translate("MainWindow", "主页"))
        self.QuizBtn_1.setText(_translate("MainWindow", "小测"))
        self.exchangeBox.setTitle(_translate("MainWindow", "变形"))
        self.exchangeEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.PreSufBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt; font-weight:600;\">词根 词缀</span></p></body></html>"))
        self.countBrowser_1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:48pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:26pt; font-style:italic;\">12</span></p></body></html>"))
        self.meaningBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-style:italic;\"><br /></p></body></html>"))
        self.ChineseBtn.setText(_translate("MainWindow", "中文"))
        self.EnglishBtn.setText(_translate("MainWindow", "英文"))
        self.quizLabel.setText(_translate("MainWindow", "TMP"))
        self.groupBox_3.setTitle(_translate("MainWindow", "词义"))
        self.meaningBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:20px; font-style:italic;\"><br /></p></body></html>"))
        self.MenuBtn_2.setText(_translate("MainWindow", "主页"))
        self.remainLabel.setText(_translate("MainWindow", "剩余:"))
        self.greatSentenceCHI.setText(_translate("MainWindow", "凡是决心取得胜利的人是从来不说“不可能”的。（拿破仑）"))
        self.greatSentenceEng.setText(_translate("MainWindow", "The man who has made up his mind to win will never say “ Impossible”.（ Napoleon ）"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">上传：</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">下载：</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">+</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">关闭：</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">+</span></p></body></html>"))
        self.toolButton_4.setText(_translate("MainWindow", "Ctrl"))
        self.toolButton_3.setText(_translate("MainWindow", "U"))
        self.toolButton_7.setText(_translate("MainWindow", "X"))
        self.toolButton_6.setText(_translate("MainWindow", "Ctrl"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">+</span></p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "Ctrl"))
        self.toolButton_5.setText(_translate("MainWindow", "D"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">在左侧选择一本单词书</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">或者点击上传按钮 上传自己的单词书</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">自己的单词书必须是excel形式（*.xlsx）</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">第一列： 单词</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">第二列： 词性</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">第三列： 词义</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">单词为必填项</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Times New Roman\'; font-size:20pt; font-weight:600;\">快捷键👇</span></p></body></html>"))
